### ISSUE TITLE
Implement destroy() method for pimatic 0.9

### ISSUE THREAD

**Issue by mwittig** [360manu/pimatic-mythermostat#1]
For pimatic 0.9 your MyHeatingThermostat device needs to implement a destroy method as follows:

```
destroy: () ->
  # shutdown device, i.e., remove Timers, de-register event handlers registered with the framework
  super()
```

 I have quickly reviewed your code and as far as I understand this you need to deregister the event callback functions for "variableAdded" and ""variableValueChanged" in  _startObservation(). Moreover, you need call @modeSchedule.stop() and @modeManual.stop().

**Comment by 360manu** [comment]
Hello

It's done.
Thanks
